const dictionary = ["ABENDMUSIK", "ABENDMUSIKEN", "ABITUR", "ABITURS", "ABSEIL", "ABSEILED", "ABSEILER", "ABSEILERS", "ABSEILING", "ABSEILINGS", "ABSEILS", "AFFENPINSCHER", "AFFENPINSCHERS", "AMTMAN", "AMTMANS", "ANLAGE", "ANLAGEN", "ANLAGES", "ANSATZ", "ANSCHAUUNG", "ANSCHAUUNGEN", "APFELSTRUDEL", "APFELSTRUDELS", "AUF", "AUFGABE", "AUFGABEN", "AUFGABES", "AUFGEHOBEN", "AUFHEBUNG", "AUFHEBUNGEN", "AUFS", "AUFWUCHS", "AUSDRUCKSTANZ", "AUSDRUCKSTANZE", "AUTOBAHN", "AUTOBAHNEN", "AUTOBAHNS", "BAUMKUCHEN", "BEREITSCHAFTSPOTENTIAL", "BEREITSCHAFTSPOTENTIALS", "BERGFALL", "BERGFALLS", "BERGSCHRUND", "BERGSCHRUNDS", "BESTICK", "BESTICKING", "BESTICKS", "BESTUCK", "BEWUSSTSEINSLAGE", "BEWUSSTSEINSLAGEN", "BI-LIPSCHITZ", "BIERKELLER", "BIERKELLERS", "BIERWURST", "BIERWURSTS", "BILDUNGSROMAN", "BILDUNGSROMANE", "BILIPSCHITZ", "BISMARCK", "BISMARCKS", "BLECH", "BLITZKRIEG", "BLITZKRIEGS", "BLUTWURST", "BLUTWURSTS", "BONSPIEL", "BONSPIELS", "BRATWURST", "BRATWURSTS", "BRAUNSCHWEIGER", "BRAUNSCHWEIGERS", "BREMSSTRAHLUNG", "BREMSSTRAHLUNGS", "BUHR", "BUHRS", "BUTTERBROT", "BUTTERBROTS", "C-STOFF", "CAPELLMEISTER", "CAPELLMEISTERS", "CARLOWITZ", "CARLOWITZES", "CHRISTKINDLESMARKT", "CHRISTKINDLESMARKTE", "CHRISTKINDLIMARKT", "CHRISTKINDLIMARKTE", "CHRISTKINDLMARKET", "CHRISTKINDLMARKETS", "CHRISTKINDLMARKT", "CHRISTKINDLMARKTE", "CURRYWURST", "CURRYWURSTS", "DAUERSCHLAF", "DELICATESSEN", "DELICATESSENS", "DIRNDL", "DIRNDLS", "DOBERMAN", "DOBERMANN", "DOBERMANNS", "DOBERMANS", "DRAHTHAAR", "DRAHTHAARS", "DREIKANTER", "DREIKANTERS", "DUMMKOPF", "DUMMKOPFS", "DURCHKOMPONIERT", "DURST", "EDELWEISS", "EDELWEISSES", "EDELZWICKER", "EIGENBASES", "EIGENBASIS", "EIGENCLASS", "EIGENCLASSES", "EIGENCURVE", "EIGENCURVES", "EIGENDECOMPOSITION", "EIGENDECOMPOSITIONS", "EIGENFACE", "EIGENFACES", "EIGENFORM", "EIGENFORMS", "EIGENFREQUENCIES", "EIGENFREQUENCY", "EIGENFUNCTION", "EIGENFUNCTIONS", "EIGENGAP", "EIGENGAPS", "EIGENGRAU", "EIGENGRAUS", "EIGENIMAGE", "EIGENIMAGES", "EIGENKET", "EIGENKETS", "EIGENLICHT", "EIGENLICHTS", "EIGENMODE", "EIGENMODES", "EIGENOPERATOR", "EIGENOPERATORS", "EIGENSPACE", "EIGENSPACES", "EIGENSPECTRA", "EIGENSPECTRUM", "EIGENSPINOR", "EIGENSPINORS", "EIGENSTRAIN", "EIGENSTRAINS", "EIGENSTRUCTURE", "EIGENSTRUCTURES", "EIGENSUBSPACE", "EIGENSUBSPACES", "EIGENTONE", "EIGENTONES", "EIGENVALUE", "EIGENVALUES", "EIGENVECTOR", "EIGENVECTORS", "EIGENVOICE", "EIGENVOICES", "EIGENWELT", "EIGENWELTS", "EINKORN", "EINKORNS", "EISWEIN", "EISWEINS", "ENTWICKLUNGSROMAN", "ENTWICKLUNGSROMANE", "ERSATZ", "FELDSCHAR", "FELDSCHARS", "FELDSCHER", "FELDSCHERS", "FELDWEBEL", "FELDWEBELS", "FESTSCHRIFT", "FESTSCHRIFTEN", "FESTSCHRIFTS", "FLAMMKUCHEN", "FLUGEL", "FLUGELHORN", "FLUGELHORNS", "FLUGELMAN", "FLUGELMEN", "FLUGELS", "FRANKFORT", "FRANKFORTS", "FRANKFURT", "FRANKFURTER", "FRANKFURTS", "FRAULEIN", "FRAULEINS", "FREMD", "FREMDS", "FUEHRER", "FUEHRERS", "FUHRER", "FUHRERPRINZIP", "FUHRERPRINZIPS", "FUHRERS", "GASTHAUS", "GASTHAUSER", "GASTHAUSES", "GAU", "GAULIETER", "GAULIETERS", "GAUS", "GEBRAUCHSMUSIK", "GEDACT", "GEDACTS", "GEDANKENEXPERIMENT", "GEDANKENEXPERIMENTS", "GEDECKT", "GEDECKTS", "GEFULLTE", "GEGENSCHEIN", "GEGENSCHEINS", "GEGENSTANDSTHEORIE", "GEGENSTANDSTHEORIES", "GELANDESPRUNG", "GELANDESPRUNGS", "GEMEINSCHAFT", "GEMEINSCHAFTEN", "GEMEINSCHAFTSGEFUHL", "GEMEINSCHAFTSGEFUHLE", "GEMUTLICHKEIT", "GEMUTLICHKEITEN", "GESAMTKUNSTWERK", "GESAMTKUNSTWERKS", "GESELLSCHAFT", "GESELLSCHAFTEN", "GESUNDHEIT", "GEWURZTRAMINER", "GEWURZTRAMINERS", "GLOCKENSPIEL", "GLOCKENSPIELS", "GLUHWEIN", "GLUHWEINS", "GUGELHUPF", "GUGELHUPFS", "GUGLHUPF", "GUGLHUPFS", "HAKENKREUZ", "HAKENKREUZES", "HAKENKREUZLER", "HAKENKREUZLERS", "HALBERD", "HALBERDS", "HALBERT", "HALBERTS", "HASENPFEFFER", "HAUSFRAU", "HAUSFRAUEN", "HEILIGENSCHEIN", "HEILIGENSCHEINS", "HERRENVOLK", "HERRENVOLKS", "HINTERLAND", "HINTERLANDS", "HOCHSTIFT", "HOCHSTIFTE", "HOFBRAU", "HOFBRAUHAUS", "HOFBRAUHAUSER", "HOFBRAUS", "HOHLRAUM", "HOHLRAUMS", "HONIGKUCHEN", "INFAUST", "INFOBAHN", "INFOBAHNS", "INSELBERG", "INSELBERGE", "iNSELBERGS", "JAEGER", "JAEGERS", "JAGDTERRIER", "JAGDTERRIERS", "JAGDWURST", "JAGDWURSTS", "JAGER", "JUGENDSTIL", "JUGENDSTILS", "KAFFEEKLATSCH", "KAFFEEKLATSCHEN", "KAFFEEKLATSCHES", "KAISERSCHMARRN", "KAMERAD", "KAMERADED", "KAMERADING", "KAMERADS", "KAPELLMEISTER", "KAPELLMEISTERS", "KATZBALGER", "KATZBALGERS", "KATZENJAMMER", "KATZENJAMMERS", "KERNMANTEL", "KIESELGUHR", "KIESELGUHRS", "KINDERSPIEL", "KINDERSPIELS", "KIRSCHWASSER", "KIRSCHWASSERS", "KITSCH", "KITSCHES", "KLANGFARBE", "KLANGFARBES", "KLATSCH", "KLATSCHES", "KLETTERSCHUH", "KLETTERSCHUHE", "KNACKWURST", "KNACKWURSTS", "KNOCKWURST", "KNOCKWURSTS", "KOCHWURST", "KOCHWURSTS", "KRAFT", "KRAFTS", "KRANZ", "KRANZES", "KREUZER", "KREUZERS", "KRIEGSPIEL", "KRIEGSPIELS", "KRIEGSSPIEL", "KRIEGSSPIELS", "KROMFOHRLANDER", "KROMFOHRLANDERS", "KRUMMHOLZ", "KRUMMHORN", "KRUMMHORNS", "KUCHEN", "KUCHENS", "KUGELHOPF", "KUGELHOPS", "KULTURKAMPF", "KULTURKAMPFES", "KULTURKAMPFS", "KULTURKREIS", "KULTURKREISE", "KUMMERBUND", "KUMMERBUNDS", "KUNSTKAMMER", "KUNSTKAMMERN", "LACHSSCHINKEN", "LANDESHAUPTFRAU", "LANDESHAUPTFRAUEN", "LANDESHAUPTLEUTE", "LANDESHAUPTMANN", "LANDESHAUPTMANNER", "LANDJAEGER", "LANDJAGER", "LANDJAGERS", "LANDSKNECHT", "LANDSKNECHTS", "LANGLAUF", "LANGLAUS", "LANGSPIEL", "LANGSPIELS", "LAUF", "LAUFS", "LAUWINE", "LAUWINES", "LEBEN", "LEBENS", "LEBENSRAUM", "LEBENSRAUMS", "LEBENSWELT", "LEBENSWELTEN", "LEBKUCHEN", "LEBKUCHENHERZ", "LEBKUCHENHERZEN", "LEBKUCHENHERZES", "LEBKUCHENS", "LEHR", "LEHRJAHRE", "LEHRMAN", "LEHRMEN", "LEHRS", "LEITMOTIF", "LEITMOTIFS", "LEITMOTIV", "LEITMOTIVS", "LICHT", "LICHTS", "LIEBFRAUENMILCH", "LIEBFRAUENMILCHS", "LIEBFRAUMILCH", "LIEBFRAUMILCHS", "LIPSCHITZ", "LIPSCHITZNESS", "LIPSCHITZNESSES", "LUFTMENSCH", "LUFTMENSCHEN", "LUMPENPROLETARIAT", "LUMPENPROLETARIATS", "MACHE", "MACHTPOLITIK", "MACHTPOLITIKS", "MANGEL-WURZEL", "MANGEL-WURZELS", "MARGRAVE", "MARGRAVES", "MEERSCHAUM", "MEERSCHAUMS", "MEISTER", "MEISTERGENSANGE", "MEISTERGESANG", "MEISTERS", "METTWURST", "MILCHIG", "MORGENSTERN", "MORGENSTERNS", "MOZARTKUGEL", "MOZARTKUGELN", "NACHSCHLAG", "NACHSCHLAGS", "NATUR-PHILOSOPHIE", "NATUR-PHILOSOPHIEN", "NATURPHILOSOPHIE", "NATURPHILOSOPHIEN", "NEBEL", "NEBELS", "NIETZSCHEAN", "NIETZSCHEANISM", "NIETZSCHEANISMS", "NIETZSCHEANS", "OKTOBERFEST", "OKTOBERFESTS", "PALSGRAVE", "PALSGRAVES", "PASSIVHAUS", "PASSIVHAUSES", "PFEFFERKUCHEN", "PFENNIG", "PFENNIGE", "PFENNIGS", "PINSCHER", "PINSCHERS", "POLTERGEIST", "POLTERGEISTS", "PUTSCH", "PUTSCHES", "PUTSCHIST", "PUTSCHISTS", "QUETSCH", "QUETSCHES", "RAUSCHPFEIFE", "RAUSCHPFEIFEN", "REALPOLITIK", "REALPOLITIKER", "REALPOLITIKERS", "REALPOLITIKS", "REICHSLAND", "REICHSLANDS", "REICHSMARK", "REICHSMARKS", "RIESLING", "RIESLINGS", "RITTER", "RITTERS", "RORT", "RORTED", "RORTING", "RORTINGS", "ROTTWEILER", "RUDESHEIMER", "RUDESHEIMERS", "SAUERBRATEN", "SAUERBRATENS", "SAUERKRAUT", "SAUERKRAUTS", "SCHADENFREUDE", "SCHADENFREUDES", "SCHAFKOPF", "SCHAFSKOPF", "SCHERENSCHNITTE", "SCHERENSCHNITTES", "SCHERZO", "SCHERZOS", "SCHLAGER", "SCHLAGERS", "SCHLIERE", "SCHLIEREN", "SCHLIERES", "SCHLOSS", "SCHLOSSES", "SCHMALZ", "SCHMALZES", "SCHMALZIER", "SCHMALZIEST", "SCHMALZY", "SCHMATTE", "SCHMATTES", "SCHNAPPER", "SCHNAPPERS", "SCHNAPPS", "SCHNAPPSES", "SCHNAPS", "SCHNAPSES", "SCHNAUZER", "SCHNAUZERS", "SCHNITZEL", "SCHNITZELS", "SCHOTTISCHE", "SCHOTTISCHES", "SCHREKLICH", "SCHROD", "SCHRODS", "SCHUETZENFEST", "SCHUETZENFESTE", "SCHUETZENFESTS", "SCHUHPLATTLER", "SCHUHPLATTLERS", "SCHUPFNUDEL", "SCHUPFNUDELN", "SCHUSS", "SCHUSSES", "SCHUTZENFEST", "SCHUTZENFESTE", "SCHUTZENFESTS", "SCHUTZHUND", "SCHWARMEREI", "SCHWARMEREIS", "SCHWARMERISCH", "SCHWARTZ", "SCHWARTZE", "SCHWARZBIER", "SCHWARZBIERS", "SEHNSUCHT", "SICHT", "SICHTED", "SICHTS", "SINGSPIEL", "SINGSPIELE", "SINGSPIELS", "SITZFLEISCH", "SITZKRIEG", "SITZKRIEGS", "SITZMARK", "SITZMARKS", "SITZPROBE", "SITZPROBES", "SPAETZLE", "SPAETZLES", "SPATZLE", "SPATZLES", "SPINNBARKEIT", "SPINNBARKEITS", "SPITZ", "SPITZENBERG", "SPITZENBERGS", "SPITZENBURG", "SPITZES", "SPRACHGEFUHL", "SPRACHGEFUHLS", "SPRECHGESANG", "SPRECHGESANGS", "SPRECHSTIMME", "SPRECHSTIMMES", "STAHLHELM", "STAHLHELME", "STAHLHELMS", "STREUSEL", "STREUSELS", "STROMUHR", "STROMUHRS", "STRUDEL", "STRUDELS", "STURMER", "STURMERS", "T-STOFF", "TANZTHEATER", "TENDENZ", "TENDENZEN", "TURNVEREIN", "TURNVEREINS", "UMWELT", "UMWELTEN", "UNTERMENSCH", "UNTERMENSCHEN", "URSPRACHE", "URSPRACHES", "VERFREMDUNGSEFFEKT", "VERFREMDUNGSEFFEKTE", "VERKLEMPT", "VERKRAMP", "VERKRAMPTE", "VERKRAMPTES", "VOLK", "VOLKS", "VOLKSGEIST", "VOLKSGEISTER", "VOLKSGEMEINSCHAFT", "VOLKSGEMEINSCHAFTEN", "VOLKSLIED", "VOLKSLIEDER", "VOLKSLIEDERS", "WALDFLUTE", "WALDFLUTES", "WALDGRAVE", "WALDGRAVES", "WALDHORN", "WALDHORNS", "WALDRAPP", "WALDRAPPS", "WALPURGISNACHT", "WALPURGISNACHTE", "WANDERJAHR", "WANDERJAHRE", "WANDERLUST", "WANDERLUSTS", "WAPINSCHAW", "WAPINSCHAWS", "WAPPENSCHAW", "WAPPENSCHAWING", "WAPPENSCHAWINGS", "WAPPENSCHAWS", "WEDEL", "WEDELING", "WEDELN", "WEDELS", "WEHRLITE", "WEHRLITES", "WEIHNACHTSMARKT", "WEIHNACHTSMARKTE", "WEIMARANER", "WEIMARANERS", "WEISE", "WEISED", "WEISEMHEIMERS", "WEISENHEIMER", "WEISES", "WEISSBIER", "WEISSWURST", "WEIZE", "WEIZED", "WEIZES", "WEIZING", "WELTANSCHAUUNG", "WELTANSCHAUUNGEN", "WELTSCHMERZ", "WELTSCHMERZEN", "WELTSCHMERZES", "WETTER", "WETTERS", "WIENERWURST", "WIESSBIERS", "WISSENSCHAFT", "WITZELSUCHT", "WUNDER", "WUNDERKAMMER", "WUNDERKAMMERN", "WUNDERKIND", "WUNDERKINDER", "WUNDERKINDS", "WUNDERWAFFE", "WUNDERWAFFEN", "WURST", "WURSTS", "WURZEL", "WURZELS", "ZEITGEBER", "ZEITGEBERS",  "ZEITGEIST", "ZIMTSTERN", "ZIMTSTERNE", "ZITTERBEWEGUNG", "ZITTERBEWEGUNGEN", "ZUGZWANG", "ZUGZWANGED", "ZUGZWANGING", "ZUGZWANGS", "ZWEIGELT", "ZWEIGELTS","ZWEIHANDER", "ZWEIHANDERS", "ZWERGSPITZ", "ZWERGSPITZES", "ZWETSCHGENKUCHEN", "ZWIEBACK", "ZWIEBACKS", "ZWISCHENZUG", "ZWISCHENZUGS"];

let hintInterval = null;
let lastSyllable = null;

function get_syl() {
  const el = document.getElementsByClassName("syllable")[0];
  return el ? el.innerText.trim() : "";
}

function answer() {
  const currentSyllable = get_syl();
  if (!currentSyllable) return;

  if (currentSyllable === lastSyllable) return;
  lastSyllable = currentSyllable;

  const words = dictionary.filter(word =>
    word.includes(currentSyllable.toUpperCase())
  );

  const top = document.querySelector(".quickRules");
  if (!top) return;

  let ans = document.getElementById("ans");
  if (!ans) {
    ans = document.createElement("p");
    ans.id = "ans";
    top.appendChild(ans);
  }

  if (words.length === 0) {
    ans.innerText = "No match found";
    return;
  }

  let text = "Words:\n";

  const len = Math.min(6, words.length);

  for (let i = 0; i < len; i++) {
    const index = Math.floor(Math.random() * words.length);
    text += words[index];

    if (i < len - 1) text += ", ";
    if (i === 2) text += "\n";
  }

  ans.innerText = text;
}

function start() {
  if (hintInterval) return;

  hintInterval = setInterval(answer, 300);
}

chrome.runtime.onMessage.addListener((request) => {
  if (request.greeting === "toggle") {
    if (hintInterval) {
      clearInterval(hintInterval);
      hintInterval = null;
    } else {
      start();
    }
  }
});

window.addEventListener("load", start);
